routes/admin.php
<?php

use App\Http\Controllers\Admin\Auth\LoginController;
use App\Http\Controllers\Admin\HomeController;
use App\Http\Controllers\Admin\IncomesController;
use App\Http\Controllers\Admin\PaymentsController;
use App\Http\Controllers\Admin\PrimesController;
use App\Http\Controllers\Admin\ProfileController;
use App\Http\Controllers\Admin\SettingsController;
use App\Http\Controllers\Admin\UsersController;
use App\Http\Controllers\Admin\WithdrawalsController;
use App\Http\Controllers\LivewireFrame\LivewireFrameController;
use Illuminate\Support\Facades\Route;


Route::prefix('vemma/admin')
    ->name('admin.')
    ->group(function () {

        Route::middleware('guest-admin')
            ->group(function () {
                Route::get('/login', [LoginController::class, 'create'])->name('login');

                Route::post('/login', [LoginController::class, 'store']);
            });

        Route::post('/logout', [LoginController::class, 'destroy'])
            ->middleware('auth-admin:admin')
            ->name('logout');

        Route::middleware('auth-admin:admin')
            ->group(function () {
                Route::get('', [HomeController::class, 'index'])->name('home');
                Route::get('users', [UsersController::class, 'index'])->name('users');
                Route::get('users/{username}', [UsersController::class, 'show'])->name('users.show');
                Route::put('users/{username}/method', [UsersController::class, 'storeMethod'])->name('users.show.method');
                Route::delete('users/method/{id}/', [UsersController::class, 'deleteMethod'])->name('users.show.method.delete');

                Route::get('users/bonus/{user}', [UsersController::class, 'userBonus'])->name('users.bonus');
                Route::post('users/bonus/{user}/{prime}', [UsersController::class, 'storeUserBonus']);

                Route::get('payments', [PaymentsController::class, 'index'])->name('payments');
                Route::post('payments/{user}', [PaymentsController::class, 'store'])->name('payments.store');
                Route::put('payments/options', [PaymentsController::class, 'storeOptions'])->name('payments.options');

                Route::put('payments/method', [PaymentsController::class, 'storeMethod'])->name('payments.method');
                Route::delete('payments/method/{id}', [PaymentsController::class, 'deleteMethod'])->name('payments.method.delete');

                Route::get('withdrawals', [WithdrawalsController::class, 'index'])->name('withdrawals');

                Route::get('incomes', [IncomesController::class, 'index'])->name('incomes');

                Route::get('primes', [PrimesController::class, 'index'])->name('primes');
                Route::post('primes', [PrimesController::class, 'storePrime']);
                Route::delete('primes/{id}', [PrimesController::class, 'destroyPrime'])->name('primes.delete');

                Route::post('advantages', [PrimesController::class, 'storeAdvantage'])->name('advantages');
                Route::delete('advantages/{id}', [PrimesController::class, 'destroyAdvantage'])->name('advantages.delete');

                Route::get('profile', [ProfileController::class, 'index'])->name('profile');
                Route::put('profile', [ProfileController::class, 'update']);
                Route::put('profile/password', [ProfileController::class, 'changePassword'])->name('profile.password');

                Route::get('settings', [SettingsController::class, 'index'])->name('settings');
                Route::post('settings/admins', [SettingsController::class, 'store'])->name('settings.admins');
                Route::post('settings/admins/{admin}', [SettingsController::class, 'updatePassword'])->name('settings.admins.password');
            });
    });


Route::middleware('auth-admin:admin')
    ->prefix('livewire-frame')
    ->group(function () {
        Route::get('', LivewireFrameController::class)->name('livewire-frame');
    });

routes/web.php
<?php

use App\Http\Controllers\Dashboard\EncashmentController;
use App\Http\Controllers\Dashboard\GenealogyController;
use App\Http\Controllers\Dashboard\HomeController as DashboardHomeController;
use App\Http\Controllers\Dashboard\Settings\ChangePasswordController;
use App\Http\Controllers\Dashboard\Settings\ProfileController;
use App\Http\Controllers\HomeController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [HomeController::class, 'index']);

Route::middleware(['auth'])
    ->prefix('dashboard')
    ->name('dashboard.')
    ->group(function () {
        Route::get('', [DashboardHomeController::class, 'index'])->name('home');
        Route::get('genealogy', [GenealogyController::class, 'index'])->name('genealogy');
        Route::get('encashment', [EncashmentController::class, 'index'])->name('encashment');
        Route::post('encashment', [EncashmentController::class, 'store']);

        Route::prefix('settings')
            ->name('settings.')
            ->group(function () {
                Route::get('change-password', [ChangePasswordController::class, 'index'])->name('change-password');
                Route::put('change-password', [ChangePasswordController::class, 'update']);

                Route::get('profile', [ProfileController::class, 'index'])->name('profile');
                Route::put('profile', [ProfileController::class, 'update']);
                Route::post('profile/image', [ProfileController::class, 'uploadImage'])->name('profile.image');
            });
    });

require __DIR__ . '/auth.php';
require __DIR__ . '/admin.php';

resources/views/pages/admin/home.blade.php
<x-admin-layout>
    <div data-controller="admin--home">
        @include('pages.admin.home.cards')
        @include('pages.admin.home.charts')
    </div>
</x-admin-layout>

resources/views/pages/admin/incomes.blade.php
<x-admin-layout>
    <x-breadcrumb :items="[
        [
            'name' => 'Revenus',
            'active' => true
        ]
    ]" />

    <x-livewire.frame ref="tables.incomes-table" />
</x-admin-layout>

resources/views/pages/admin/payments.blade.php
<x-admin-layout>
    <x-breadcrumb :items="[
        [
            'name' => 'Paiements',
            'active' => true
        ]
    ]" />

    <div data-controller="admin--payments">
        <x-nav-tab :tabs="['Paiements', 'Nouveau Paie', 'Options', 'Mode de paiement']">
            <x-slot name="paiements">
                <x-livewire.frame ref="tables.payments-table" />
            </x-slot>
            <x-slot name="nouveau_paie">
                <x-super-admin>
                    <div class="row justify-content-center">
                        <div class="col-lg-7">
                            <x-livewire.frame frameId="users-search-table" ref="tables.payments.users-search-table" />
                        </div>
                    </div>
                </x-super-admin>
            </x-slot>
            <x-slot name="options">
                <x-super-admin>
                    <div class="row">
                        <div class="col-lg-6 mb-4">
                            <x-flash-alert type="success" session="updated" />
                            <x-flash-alert type="danger" session="error" />
                            <form method="POST" class="mt-4" autocomplete="off"
                                action="{{ route('admin.payments.options') }}">
                                @csrf
                                @method('PUT')
                                <div class="mb-3">
                                    <x-label>
                                        {{ __("Definier le montant que l'Définir le montant que l'utilisateur devra payer lors de l'activation de son compte.") }}
                                    </x-label>
                                    <x-input model="user_payment" type="text"
                                        value="{{ old('user_payment') ?: ($setting ? $setting->user_payment : '0') }}"
                                        label="Paiement de l'utilisateur" />
                                </div>

                                <div class="mb-3">
                                    <x-label>
                                        {{ __("Définir le montant en pourcentage qui sera utilisé dans le calcul de balance après l'achèvement d'arborescence de l'utilisateur.") }}
                                        @if ($setting)
                                        <br>
                                        Ex:
                                        <b>
                                            <span>
                                                {{ $setting->user_percentage }} x
                                                ({{ $setting->user_payment }} x {{ $childTree }}) / {{ 100 }}
                                            </span>
                                            <span>=</span>
                                            <span>{{ $currency }}{{ $setting->user_percentage * ( $setting->user_payment * $childTree) / 100 }}</span>
                                        </b>
                                        @endif
                                    </x-label>
                                    <x-input model="user_percentage" type="text"
                                        value="{{ old('user_percentage') ?: ($setting ? $setting->user_percentage : '0') }}"
                                        label="Pourcentage d'utilisateurs (%)" />
                                </div>

                                <div class="mb-3">
                                    <x-button type="submit">
                                        {{ __("Enregistrer")}}
                                    </x-button>
                                </div>
                            </form>
                        </div>
                    </div>
                </x-super-admin>
            </x-slot>

            <x-slot name="mode_de_paiement">
                <x-super-admin>
                    <div class="row">
                        <div class="col-lg-6 mb-3">
                            <h6>{{ __("Mode de paiement") }}</h6>
                            <x-flash-alert type="success" session="created" />
                            <form method="POST" class="mt-4" autocomplete="off"
                                action="{{ route('admin.payments.method') }}">
                                @csrf
                                @method('PUT')
                                <div class="mb-3">
                                    <x-input model="method" type="text" value="{{ old('method') ?: '' }}"
                                        label="Nom de la méthode" />
                                </div>
                                <div class="mb-3">
                                    <x-button type="submit">
                                        {{ __("Enregistrer")}}
                                    </x-button>
                                </div>
                            </form>
                        </div>
                        <div class="col-lg-6">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th scope="col">{{ __("Méthode") }}</th>
                                        <th scope="col">{{ __("Supprimer") }}</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($methods as $method)
                                    <tr>
                                        <td>{{ $method->method }}</td>
                                        <td>
                                            <form method="POST" onsubmit="return confirm('{{ __('Supprimer ?') }}')"
                                                autocomplete="off"
                                                action="{{ route('admin.payments.method.delete', ['id' => $method->id]) }}">
                                                @csrf
                                                @method('DELETE')
                                                <button type="submit" class="btn btn-danger text-sm btn-sm">
                                                    {{ __("Supprimer") }}
                                                </button>
                                            </form>
                                        </td>
                                    </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </x-super-admin>
            </x-slot>
        </x-nav-tab>
    </div>
</x-admin-layout>

resources/views/pages/admin/primes.blade.php
<x-admin-layout>
    <x-breadcrumb :items="[
        [
            'name' => 'Primes',
            'active' => true
        ]
    ]" />

    <x-nav-tab :tabs="['Bonus', 'Avantages']">

        <x-slot name="bonus">
            <x-flash-alert type="danger" session="error" />
            <x-flash-alert type="success" session="created" />
            <div class="row">
                <div class="col-lg-6">
                    <form method="POST" class="mb-4" autocomplete="off" action="{{ route('admin.primes') }}">
                        @csrf
                        <div class="mb-3">
                            <x-input model="label" type="text" value="{{ old('label') ?: '' }}"
                                label="Label(ex: TV, Smartphone)" />
                        </div>
                        <div class="mb-3">
                            <x-input model="downlines" type="number" value="{{ old('downlines') ?: '' }}"
                                label="Downlines" />
                        </div>

                        <div class="mb-3">
                            <x-button type="submit">
                                {{ __("Enregistrer")}}
                            </x-button>
                        </div>
                    </form>
                </div>
                <div class="col-lg-6">
                    <table class="table">
                        <thead>
                            <tr>
                                <th scope="col">{{ __("Downlines") }}</th>
                                <th scope="col">{{ __("Label") }}</th>
                                <th scope="col">{{ __("Supprimer") }}</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($primes as $prime)
                            <tr>
                                <td>{{ $prime->downlines }}</td>
                                <td>{{ $prime->label }}</td>
                                <td>
                                    <form method="POST" onsubmit="return confirm('{{ __('Supprimer ?') }}')"
                                        autocomplete="off"
                                        action="{{ route('admin.primes.delete', ['id' => $prime->id]) }}">
                                        @csrf
                                        @method('DELETE')
                                        <button type="submit" class="btn btn-danger text-sm btn-sm">
                                            {{ __("Supprimer") }}
                                        </button>
                                    </form>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </x-slot>


        <x-slot name="avantages">
            <x-flash-alert type="danger" session="error" />
            <x-flash-alert type="success" session="created" />
            <div class="row">
                <div class="col-lg-6">
                    <form method="POST" class="mb-4" autocomplete="off" action="{{ route('admin.advantages') }}">
                        @csrf
                        <div class="mb-3">
                            <x-input model="amount" type="text" value="{{ old('amount') ?: '' }}" label="Montant" />
                        </div>
                        <div class="mb-3">
                            <x-input model="downlines" type="number" value="{{ old('downlines') ?: '' }}"
                                label="Downlines" />
                        </div>

                        <div class="mb-3">
                            <x-button type="submit">
                                {{ __("Enregistrer")}}
                            </x-button>
                        </div>
                    </form>
                </div>
                <div class="col-lg-6">
                    <table class="table">
                        <thead>
                            <tr>
                                <th scope="col">{{ __("Downlines") }}</th>
                                <th scope="col">{{ __("Montant") }}</th>
                                <th scope="col">{{ __("Supprimer") }}</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($advantages as $advantage)
                            <tr>
                                <td>{{ $advantage->downlines }}</td>
                                <td>{{ $advantage->amount }}</td>
                                <td>
                                    <form method="POST" onsubmit="return confirm('{{ __('Supprimer ?') }}')"
                                        autocomplete="off"
                                        action="{{ route('admin.advantages.delete', ['id' => $advantage->id]) }}">
                                        @csrf
                                        @method('DELETE')
                                        <button type="submit" class="btn btn-danger text-sm btn-sm">
                                            {{ __("Supprimer") }}
                                        </button>
                                    </form>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </x-slot>
    </x-nav-tab>
</x-admin-layout>

resources/views/pages/admin/profile.blade.php
<x-admin-layout>
    <div class="row">
        <div class="col-lg-5 col-md-8">
            <x-flash-alert type="success" session="updated" />
        </div>
    </div>

    <x-nav-tab :tabs="['Profil', 'Changer le mot de passe']">
        <x-slot name="profil">
            <x-dash-card title="Profil">
                <div class="row">
                    <div class="col-lg-5 col-md-8">
                        <form method="POST" class="mt-4" action="{{ route('admin.profile') }}">
                            @method('PUT')
                            @csrf

                            <div class="mb-3">
                                <x-input model="name" type="text" value="{{ old('name') ?: $auth->name }}"
                                    inputLabel="Nom" />
                            </div>

                            <div class="mb-3">
                                <x-input model="email" type="email" readonly="" value="{{ $auth->email }}"
                                    inputLabel="Adresse e-mail" />
                            </div>

                            <div class="mb-3">
                                <x-button type="submit">
                                    {{ __("Enregistrer")}}
                                </x-button>
                            </div>
                        </form>
                    </div>
                </div>
            </x-dash-card>
        </x-slot>

        <x-slot name="changer_le_mot_de_passe">
            <x-dash-card title="Changer le mot de passe">

                <div class="row">
                    <div class="col-lg-5 col-md-8">
                        <form method="POST" class="mt-4" action="{{ route('admin.profile.password') }}">
                            @method('PUT')
                            @csrf

                            <div class="mb-3">
                                <x-input model="password" type="password" inputLabel="Mot de passe actuel" />
                            </div>

                            <div class="mb-3">
                                <x-input model="password" type="password" inputLabel="Nouveau mot de passe" />
                            </div>

                            <div class="mb-3">
                                <x-input model="new_password_confirmation" type="password"
                                    inputLabel="Confirmez le mot de passe" />
                            </div>

                            <div class="mb-3">
                                <x-button type="submit">
                                    {{ __("Sauvegarder les modifications")}}
                                </x-button>
                            </div>
                        </form>
                    </div>
                </div>
            </x-dash-card>
        </x-slot>
    </x-nav-tab>
</x-admin-layout>

resources/views/pages/admin/settings.blade.php
<x-admin-layout>
    <div data-controller="admin--settings">
        <x-nav-tab :tabs="['Nouveau administrateur', 'Administrateurs']">

            <x-slot name="nouveau_administrateur">
                <x-dash-card title="Nouveau administrateur">
                    <x-flash-alert type="danger" session="error" />
                    <x-flash-alert type="success" session="created" />

                    <div class="row">
                        <div class="col-lg-5 col-md-8">
                            <form method="POST" class="mt-4" action="{{ route('admin.settings.admins') }}">
                                @csrf

                                <div class="mb-3">
                                    <x-input model="name" type="text" value="{{ old('name') ?: '' }}"
                                        inputLabel="Nom" />
                                </div>

                                <div class="mb-3">
                                    <x-input model="email" type="email" value="{{ old('email') ?: '' }}"
                                        inputLabel="Adresse e-mail" />
                                </div>

                                <div class="mb-3">
                                    <x-input model="password" type="password" inputLabel="Mot de passe" />
                                </div>

                                <div class="mb-3">
                                    <x-input model="password_confirmation" type="password"
                                        inputLabel="Confirmez le mot de passe" />
                                </div>

                                <div class="mb-3">
                                    <x-button type="submit">
                                        {{ __("Enregistrer")}}
                                    </x-button>
                                </div>
                            </form>
                        </div>
                    </div>
                </x-dash-card>
            </x-slot>

            <x-slot name="administrateurs">
                <x-super-admin>
                    <x-livewire.frame ref="tables.admins-table" />
                </x-super-admin>
            </x-slot>

        </x-nav-tab>
    </div>
</x-admin-layout>

resources/views/pages/admin/withdrawals.blade.php
<x-admin-layout>
    <x-breadcrumb :items="[
        [
            'name' => 'Retraits',
            'active' => true
        ]
    ]" />

    <x-livewire.frame ref="tables.withdrawals-table" />
</x-admin-layout>