routes/admin.php
<?php

use App\Http\Controllers\Admin\Auth\LoginController;
use App\Http\Controllers\Admin\HomeController;
use App\Http\Controllers\Admin\IncomesController;
use App\Http\Controllers\Admin\PaymentsController;
use App\Http\Controllers\Admin\PrimesController;
use App\Http\Controllers\Admin\ProfileController;
use App\Http\Controllers\Admin\SettingsController;
use App\Http\Controllers\Admin\UsersController;
use App\Http\Controllers\Admin\WithdrawalsController;
use App\Http\Controllers\LivewireFrame\LivewireFrameController;
use Illuminate\Support\Facades\Route;


Route::prefix('vemma/admin')
    ->name('admin.')
    ->group(function () {

        Route::middleware('guest-admin')
            ->group(function () {
                Route::get('/login', [LoginController::class, 'create'])->name('login');

                Route::post('/login', [LoginController::class, 'store']);
            });

        Route::post('/logout', [LoginController::class, 'destroy'])
            ->middleware('auth-admin:admin')
            ->name('logout');

        Route::middleware('auth-admin:admin')
            ->group(function () {
                Route::get('', [HomeController::class, 'index'])->name('home');
                Route::get('users', [UsersController::class, 'index'])->name('users');
                Route::get('users/{username}', [UsersController::class, 'show'])->name('users.show');
                Route::put('users/{username}/method', [UsersController::class, 'storeMethod'])->name('users.show.method');
                Route::delete('users/method/{id}/', [UsersController::class, 'deleteMethod'])->name('users.show.method.delete');

                Route::get('users/bonus/{user}', [UsersController::class, 'userBonus'])->name('users.bonus');
                Route::post('users/bonus/{user}/{prime}', [UsersController::class, 'storeUserBonus']);

                Route::get('payments', [PaymentsController::class, 'index'])->name('payments');
                Route::post('payments/{user}', [PaymentsController::class, 'store'])->name('payments.store');
                Route::put('payments/options', [PaymentsController::class, 'storeOptions'])->name('payments.options');

                Route::put('payments/method', [PaymentsController::class, 'storeMethod'])->name('payments.method');
                Route::delete('payments/method/{id}', [PaymentsController::class, 'deleteMethod'])->name('payments.method.delete');

                Route::get('withdrawals', [WithdrawalsController::class, 'index'])->name('withdrawals');

                Route::get('incomes', [IncomesController::class, 'index'])->name('incomes');

                Route::get('primes', [PrimesController::class, 'index'])->name('primes');
                Route::post('primes', [PrimesController::class, 'storePrime']);
                Route::delete('primes/{id}', [PrimesController::class, 'destroyPrime'])->name('primes.delete');

                Route::post('advantages', [PrimesController::class, 'storeAdvantage'])->name('advantages');
                Route::delete('advantages/{id}', [PrimesController::class, 'destroyAdvantage'])->name('advantages.delete');

                Route::get('profile', [ProfileController::class, 'index'])->name('profile');
                Route::put('profile', [ProfileController::class, 'update']);
                Route::put('profile/password', [ProfileController::class, 'changePassword'])->name('profile.password');

                Route::get('settings', [SettingsController::class, 'index'])->name('settings');
                Route::post('settings/admins', [SettingsController::class, 'store'])->name('settings.admins');
                Route::post('settings/admins/{admin}', [SettingsController::class, 'updatePassword'])->name('settings.admins.password');
            });
    });


Route::middleware('auth-admin:admin')
    ->prefix('livewire-frame')
    ->group(function () {
        Route::get('', LivewireFrameController::class)->name('livewire-frame');
    });

routes/web.php
<?php

use App\Http\Controllers\Dashboard\EncashmentController;
use App\Http\Controllers\Dashboard\GenealogyController;
use App\Http\Controllers\Dashboard\HomeController as DashboardHomeController;
use App\Http\Controllers\Dashboard\Settings\ChangePasswordController;
use App\Http\Controllers\Dashboard\Settings\ProfileController;
use App\Http\Controllers\HomeController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [HomeController::class, 'index']);

Route::middleware(['auth'])
    ->prefix('dashboard')
    ->name('dashboard.')
    ->group(function () {
        Route::get('', [DashboardHomeController::class, 'index'])->name('home');
        Route::get('genealogy', [GenealogyController::class, 'index'])->name('genealogy');
        Route::get('encashment', [EncashmentController::class, 'index'])->name('encashment');
        Route::post('encashment', [EncashmentController::class, 'store']);

        Route::prefix('settings')
            ->name('settings.')
            ->group(function () {
                Route::get('change-password', [ChangePasswordController::class, 'index'])->name('change-password');
                Route::put('change-password', [ChangePasswordController::class, 'update']);

                Route::get('profile', [ProfileController::class, 'index'])->name('profile');
                Route::put('profile', [ProfileController::class, 'update']);
                Route::post('profile/image', [ProfileController::class, 'uploadImage'])->name('profile.image');
            });
    });

require __DIR__ . '/auth.php';
require __DIR__ . '/admin.php';

app/Models/Setting.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Setting extends Model
{
    use HasFactory;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'user_payment',
        'user_percentage',
    ];
}

app/Http/Controllers/Admin/SettingsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Admin;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Gate;
use Illuminate\Support\Facades\Hash;

class SettingsController extends Controller
{
    public function index()
    {
        return view('pages.admin.settings');
    }

    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required|string|max:255|min:3',
            'email' => 'required|email|string|max:255|unique:admins',
            'password' => 'required|string|confirmed|min:6',
        ]);

        $response = Gate::inspect('super-admin');

        if (!$response->allowed()) {
            return back()->with('error', $response->message());
        }

        Admin::create([
            'name' => $request->name,
            'email' => $request->email,
            'password' => Hash::make($request->password)
        ]);

        return back(201)->with('created', trans("L'utilisateur a été créé avec succès"));
    }


    public function updatePassword(Request $request, Admin $admin)
    {
        $request->validate([
            'password' => 'required|string|confirmed|min:6'
        ]);

        $response = Gate::inspect('super-admin');

        if (!$response->allowed()) {
            return response()
                ->json(['errors' => ['password' => $response->message()]], 422);
        }

        if ($admin->id == $request->user()->id) {
            return response()
                ->json([
                    'errors' => [
                        'password' => trans("Vous ne pouvez pas modifier le mot de passe de l'utilisateur actuellement connecté.")
                    ]
                ], 422);
        }

        $admin->fill(['password' => Hash::make($request->password)])->save();

        return ['message' => trans('Mot de passe changé avec succès')];
    }
}

app/Http/Controllers/Dashboard/EncashmentController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Models\EncashmentMethod;
use App\Models\PaymentMethod;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Str;

class EncashmentController extends Controller
{
    public function index(Request $request)
    {
        $auth = $request->user();

        return view('pages.dashboard.encashment', [
            'balance' => $auth->availableBalance(),
            'methods' => $auth->encashmentMethods,
            'encashments' => $auth->encashments,
            'encashmentsTotal' => $auth->amountEncashment()
        ]);
    }

    private function errors(string $input, string $message)
    {
        return back()
            ->withErrors([$input => trans($message)])
            ->withInput();
    }

    public function store(Request $request)
    {
        $request->validate([
            'amount' => ['required', 'numeric', 'min:1'],
            'method' => ['required', 'string']
        ]);

        $user = $request->user();

        if (!$user->active) {
            return $this->errors('amount', "Vous devez activer votre compte avant de continuer.");
        }

        $supported = $this->supportedMethod($request->method);

        $method = $user->encashmentMethods()->where('method', $request->method)->first();

        if (!$supported || !$method) {
            return $this->errors('method', "La méthode utilisée n'est pas supportée.");
        }

        $balance = $user->availableBalance();

        if (doubleval($request->amount) > $balance) {
            return $this->errors('amount', "Votre solde est insuffisant par rapport au montant saisi.");
        }

        $this->encashments($user, $method, doubleval($request->amout));

        return back()
            ->with('proceed', trans("Votre demande a été exécutée avec succès"));
    }


    private function encashments(User $user, EncashmentMethod $method, float $amount)
    {
        $encashment = $user->encashments()->create([
            'amount' => $amount,
            'confirmed' => true,
            'encashment_method_id' => $method->id
        ]);

        $reference = strval($encashment->id);
        $length = 11 - strlen($reference);

        if ($length > 0) {
            $reference = Str::random($length) . $reference;
        }

        $encashment->reference = $reference;
        $encashment->save();
    }

    private function supportedMethod(string $method): bool
    {
        return PaymentMethod::where('method', $method)->exists();
    }
}

app/Http/Controllers/Dashboard/GenealogyController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Models\User;
use App\Repositories\GenealogyRepository;
use Illuminate\Http\Request;

class GenealogyController extends Controller
{
    public function index(Request $request)
    {

        $username = $request->query('username');
        $auth = $username ? User::firstWhere('username', $username) : $request->user();

        $genealogies = (new GenealogyRepository)->getConstructedTree($auth);

        $genealogiesChart = collect($genealogies)
            ->map(fn ($item) => $item ? (object) [
                'username' => $item->username,
                'fullname' => $item->fullname,
                'id' => $item->id
            ] : $item);

        return view('pages.dashboard.genealogy', compact('genealogies', 'genealogiesChart'));
    }
}

app/Http/Controllers/Dashboard/HomeController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Repositories\SettingsRepository;
use Illuminate\Http\Request;

class HomeController extends Controller
{
    public function index(Request $request)
    {
        /** @var \App\Models\User */
        $user = $request->user();

        return view('pages.dashboard.home', [
            'available_balance' => $user->availableBalance(),
            'encashment' => $user->amountEncashment(),
            'balance' => $user->amountBalance(),
            'profile' => $user->profile,
            'auth' => $user,
            'setting' => SettingsRepository::getSetting()
        ]);
    }
}

app/Http/Controllers/Dashboard/Settings/ChangePasswordController.php
<?php

namespace App\Http\Controllers\Dashboard\Settings;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;

class ChangePasswordController extends Controller
{
    public function index()
    {
        return view('pages.dashboard.settings.change-password');
    }

    public function update(Request $request)
    {
        $request->validate([
            'password' => ['required', 'string', 'max:255', 'password:web'],
            'new_password' => ['required', 'string', 'max:255', 'min:6', 'confirmed'],
        ]);

        $auth = $request->user();

        $auth->fill([
            'password' => Hash::make($request->new_password)
        ])->save();

        return back()->with('updated', trans("Mot de passe changé avec succès"));
    }
}

app/Http/Controllers/Dashboard/Settings/ProfileController.php
<?php

namespace App\Http\Controllers\Dashboard\Settings;

use App\Files\File;
use App\Http\Controllers\Controller;
use App\Rules\ValidPhone;
use Illuminate\Http\Request;

class ProfileController extends Controller
{

    public function __construct()
    {
        $this->middleware(['optimizeImages:250,90'])->only('uploadImage');
    }

    public function index(Request $request)
    {
        $auth = $request->user();

        return view('pages.dashboard.settings.profile', [
            'auth' => $auth,
            'profile' => $auth->profile
        ]);
    }

    public function update(Request $request)
    {
        $data = $request->validate([
            'firstname' => ['required', 'string', 'max:255', 'min:3'],
            'lastname' => ['required', 'string', 'max:255'],
            'middlename' => ['nullable', 'string', 'max:255'],
            'gender' => ['nullable', 'string', 'max:255', 'min:2'],
            'phone' => ['required', 'string', 'max:50', new ValidPhone],
            'birthdate' => ['required', 'string', 'date'],
            'tax_identification_number' => ['nullable', 'max:255'],
            'address' => ['nullable', 'string', 'max:255'],
            'country' => ['required', 'string', 'max:255'],
            'region' => ['required', 'string', 'max:255'],
            'description' => ['nullable', 'string', 'max:400', 'min:15']
        ]);

        $auth = $request->user();

        $auth->profile->fill($data)->save();

        return back()->with('updated', trans('Votre profil a été mis à jour avec succés'));
    }


    public function uploadImage(Request $request)
    {
        $request->validate([
            'image' => File::IMAGE_RULES
        ]);

        $auth = $request->user();
        $file = $request->file('image');

        $auth->profile->fill([
            'image' => $file->storeAs(File::IMAGES_PATH, "{$auth->username}.jpg")
        ])->save();

        return back()->with('updated', trans("Image profil téléchargé avec succès"));
    }
}

resources/views/pages/dashboard/settings/change-password.blade.php
<x-dashboard-layout>
    <x-dash-card title="Changer le mot de passe">
        <x-flash-alert type="success" session="updated" />

        <div class="row">
            <div class="col-lg-5 col-md-8">
                <form method="POST" class="mt-4" action="{{ route('dashboard.settings.change-password') }}">
                    @method('PUT')
                    @csrf

                    <div class="mb-3">
                        <x-input model="password" type="password" inputLabel="Mot de passe actuel" />
                    </div>

                    <div class="mb-3">
                        <x-input model="password" type="password" inputLabel="Nouveau mot de passe" />
                    </div>

                    <div class="mb-3">
                        <x-input model="new_password_confirmation" type="password"
                            inputLabel="Confirmez le mot de passe" />
                    </div>

                    <div class="mb-3">
                        <x-button type="submit">
                            {{ __("Sauvegarder les modifications")}}
                        </x-button>
                    </div>
                </form>
            </div>
        </div>
    </x-dash-card>
</x-dashboard-layout>

resources/views/pages/dashboard/settings/profile.blade.php
<x-dashboard-layout>
    <div data-controller="dashboard--profile">
        <x-dash-card title="Paramètres de profil">

            <x-flash-alert type="success" session="updated" />

            <form action="{{ route('dashboard.settings.profile') }}" method="post">
                @csrf
                @method("PUT")
                <div class="row">
                    <div class="col-lg-6">
                        <x-dash-card title="Renseignements personnels">

                            <div class="row">
                                <div class="mb-3 col-lg-6">
                                    <x-input model="firstname" type="text"
                                        value="{{ old('firstname') ?: $profile->firstname }}" label="Prénom" />
                                </div>
                                <div class="mb-3 col-lg-6">
                                    <x-input model="lastname" type="text"
                                        value="{{ old('lastname') ?: $profile->lastname }}" label="Nom de famille" />
                                </div>
                            </div>

                            <div class="row">
                                <div class="mb-3 col-lg-6">
                                    <x-input model="middlename" type="text"
                                        value="{{ old('middlename') ?: $profile->middlename }}" label="Autre Nom" />
                                </div>

                                <div class="mb-3 col-lg-6">
                                    <div>
                                        <label class="form-label">
                                            Sexe
                                        </label>
                                        <select class="form-select" name="gender" aria-label="Default select example">
                                            <option value="">{{ __("Sexe") }}</option>
                                            @foreach ([['name' => 'Homme', 'value' =>'male'], ['name' => 'Femme',
                                            'value' =>
                                            'female']] as $item)
                                            <option value="{{ $item['value'] }}"
                                                {{ $profile->gender == $item['value'] ? 'selected' : '' }}>
                                                {{ __($item['name']) }}
                                            </option>
                                            @endforeach
                                        </select>
                                    </div>
                                </div>
                            </div>

                            <div class="mb-3">
                                <x-input model="birthdate" type="date"
                                    value="{{ old('birthdate') ?: $profile->birthdate }}" label="Date de naissance" />
                            </div>

                            <div class="mb-3">
                                <x-input model="tax_identification_number" type="text"
                                    value="{{ old('tax_identification_number') ?: $profile->tax_identification_number }}"
                                    label="Numéro d'identification fiscale" />
                            </div>

                            <div class="mb-3">
                                <x-input model="address" type="text" value="{{ old('address') ?: $profile->address }}"
                                    label="Adresse" />
                            </div>

                            <div class="mb-3">
                                <x-input model="country" type="text" value="{{ old('country') ?: $profile->country }}"
                                    label="Pays" />
                            </div>

                            <div class="mb-3">
                                <x-input model="region" type="text" value="{{ old('region') ?: $profile->region }}"
                                    label="Région/État" />
                            </div>

                        </x-dash-card>
                    </div>
                    <div class="col-lg-6">
                        <x-dash-card title="Autres informations">
                            <div class="mb-3">
                                <x-input model="phone" type="tel" value="{{ old('phone') ?: $profile->phone }}"
                                    label="Numéro de téléphone" />
                            </div>

                            <div class="mb-3">
                                <x-input type="email" model="email" readonly=""
                                    value="{{ old('email') ?: $auth->email }}" label="Adresse e-mail" />
                            </div>

                            <div class="mb-3">
                                <label for="description" class="form-label">{{ __('À propos de moi') }}</label>
                                <textarea class="form-control @error('description') is-invalid @enderror"
                                    name="description" id="description" rows="3">
                                {{ old('description') ?: $profile->description }}
                                </textarea>
                                @error('description')<div class="invalid-feedback">{{$message}}</div>@enderror
                            </div>
                        </x-dash-card>
                    </div>
                </div>

                <div class="mb-3">
                    <x-button type="submit">
                        {{ __("Sauvegarder les modifications")}}
                    </x-button>
                </div>
            </form>
        </x-dash-card>

        <x-dash-card title="Image profil">
            <form action="{{ route('dashboard.settings.profile.image') }}" method="POST" enctype="multipart/form-data">
                @csrf
                <div class="upload--img-u">
                    <label>{{ __('Image') }} *</label>
                    <div class="upload-image">
                        <div>
                            <img {{ Auth::user()->image  ? "src=".Auth::user()->image : '' }}
                                data-dashboard--profile-target="imageDisplay" style="width: 100%; height: 100%;" />
                        </div>
                        <input type="file" data-action="dashboard--profile#onChangeImage" id="file" accept="image/*"
                            class="is-invalid file-upload-m" name="image">
                    </div>
                </div>
                @error('image')<div class="text-danger">{{$message}}</div>@enderror

                <x-button type="submit">
                    {{ __("Sauvegarder")}}
                </x-button>
            </form>
        </x-dash-card>
    </div>

</x-dashboard-layout>