routes/admin.php
<?php

use App\Http\Controllers\Admin\Auth\LoginController;
use App\Http\Controllers\Admin\HomeController;
use App\Http\Controllers\Admin\IncomesController;
use App\Http\Controllers\Admin\PaymentsController;
use App\Http\Controllers\Admin\PrimesController;
use App\Http\Controllers\Admin\ProfileController;
use App\Http\Controllers\Admin\SettingsController;
use App\Http\Controllers\Admin\UsersController;
use App\Http\Controllers\Admin\WithdrawalsController;
use App\Http\Controllers\LivewireFrame\LivewireFrameController;
use Illuminate\Support\Facades\Route;


Route::prefix('vemma/admin')
    ->name('admin.')
    ->group(function () {

        Route::middleware('guest-admin')
            ->group(function () {
                Route::get('/login', [LoginController::class, 'create'])->name('login');

                Route::post('/login', [LoginController::class, 'store']);
            });

        Route::post('/logout', [LoginController::class, 'destroy'])
            ->middleware('auth-admin:admin')
            ->name('logout');

        Route::middleware('auth-admin:admin')
            ->group(function () {
                Route::get('', [HomeController::class, 'index'])->name('home');
                Route::get('users', [UsersController::class, 'index'])->name('users');
                Route::get('users/{username}', [UsersController::class, 'show'])->name('users.show');
                Route::put('users/{username}/method', [UsersController::class, 'storeMethod'])->name('users.show.method');
                Route::delete('users/method/{id}/', [UsersController::class, 'deleteMethod'])->name('users.show.method.delete');

                Route::get('users/bonus/{user}', [UsersController::class, 'userBonus'])->name('users.bonus');
                Route::post('users/bonus/{user}/{prime}', [UsersController::class, 'storeUserBonus']);

                Route::get('payments', [PaymentsController::class, 'index'])->name('payments');
                Route::post('payments/{user}', [PaymentsController::class, 'store'])->name('payments.store');
                Route::put('payments/options', [PaymentsController::class, 'storeOptions'])->name('payments.options');

                Route::put('payments/method', [PaymentsController::class, 'storeMethod'])->name('payments.method');
                Route::delete('payments/method/{id}', [PaymentsController::class, 'deleteMethod'])->name('payments.method.delete');

                Route::get('withdrawals', [WithdrawalsController::class, 'index'])->name('withdrawals');

                Route::get('incomes', [IncomesController::class, 'index'])->name('incomes');

                Route::get('primes', [PrimesController::class, 'index'])->name('primes');
                Route::post('primes', [PrimesController::class, 'storePrime']);
                Route::delete('primes/{id}', [PrimesController::class, 'destroyPrime'])->name('primes.delete');

                Route::post('advantages', [PrimesController::class, 'storeAdvantage'])->name('advantages');
                Route::delete('advantages/{id}', [PrimesController::class, 'destroyAdvantage'])->name('advantages.delete');

                Route::get('profile', [ProfileController::class, 'index'])->name('profile');
                Route::put('profile', [ProfileController::class, 'update']);
                Route::put('profile/password', [ProfileController::class, 'changePassword'])->name('profile.password');

                Route::get('settings', [SettingsController::class, 'index'])->name('settings');
                Route::post('settings/admins', [SettingsController::class, 'store'])->name('settings.admins');
                Route::post('settings/admins/{admin}', [SettingsController::class, 'updatePassword'])->name('settings.admins.password');
            });
    });


Route::middleware('auth-admin:admin')
    ->prefix('livewire-frame')
    ->group(function () {
        Route::get('', LivewireFrameController::class)->name('livewire-frame');
    });

routes/web.php
<?php

use App\Http\Controllers\Dashboard\EncashmentController;
use App\Http\Controllers\Dashboard\GenealogyController;
use App\Http\Controllers\Dashboard\HomeController as DashboardHomeController;
use App\Http\Controllers\Dashboard\Settings\ChangePasswordController;
use App\Http\Controllers\Dashboard\Settings\ProfileController;
use App\Http\Controllers\HomeController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [HomeController::class, 'index']);

Route::middleware(['auth'])
    ->prefix('dashboard')
    ->name('dashboard.')
    ->group(function () {
        Route::get('', [DashboardHomeController::class, 'index'])->name('home');
        Route::get('genealogy', [GenealogyController::class, 'index'])->name('genealogy');
        Route::get('encashment', [EncashmentController::class, 'index'])->name('encashment');
        Route::post('encashment', [EncashmentController::class, 'store']);

        Route::prefix('settings')
            ->name('settings.')
            ->group(function () {
                Route::get('change-password', [ChangePasswordController::class, 'index'])->name('change-password');
                Route::put('change-password', [ChangePasswordController::class, 'update']);

                Route::get('profile', [ProfileController::class, 'index'])->name('profile');
                Route::put('profile', [ProfileController::class, 'update']);
                Route::post('profile/image', [ProfileController::class, 'uploadImage'])->name('profile.image');
            });
    });

require __DIR__ . '/auth.php';
require __DIR__ . '/admin.php';

resources/views/layouts/admin/navbar.blade.php
<nav class="navbar navbar-expand navbar-light bg-light mb-3">
    <div class="container-fluid">
        <div>
            <button class="custom-menu btn btn-sm d-lg-none" type="button" data-layout-target="collapse-toggle">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none"
                    stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                    class="feather feather-menu">
                    <line x1="3" y1="12" x2="21" y2="12"></line>
                    <line x1="3" y1="6" x2="21" y2="6"></line>
                    <line x1="3" y1="18" x2="21" y2="18"></line>
                </svg>
            </button>
            <div class="mx-lg-0 d-inline-block"></div>
            <a class="navbar-brand text-sm text-decoration-none mr-3" id="page_header_title" href="javascript:void(0)">
                Admin: <b>{{ Auth::user()->name }}</b>
            </a>
        </div>
        <div>
            <div class="navbar-collapse" id="navbarNav">
                <ul class="navbar-nav" style="padding-right: 15px">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle profile-dropdown admin text-decoration-none"
                            id="navbarDropdownUser" href="#" role="button" data-bs-toggle="dropdown"
                            aria-haspopup="true" aria-expanded="true">
                            {{ Auth::user()->email }}
                        </a>
                        <div class="dropdown-menu dropdown-menu-end py-0" aria-labelledby="navbarDropdownUser"
                            data-bs-popper="none">
                            <div class="bg-white rounded-2 py-2">
                                <a class="dropdown-item" href="{{ route('admin.profile') }}">
                                    {{ __("Mon Profil") }}
                                </a>
                                <a class="dropdown-item" href="{{ route('admin.settings') }}">
                                    {{ __("Paramètre") }}
                                </a>
                                <div class="dropdown-divider"></div>
                                <form method="POST" action="{{ route('admin.logout') }}">
                                    @csrf
                                    <button class="dropdown-item btn btn-link" type="submit">
                                        {{ __("Se Déconnecter") }}
                                    </button>
                                </form>
                            </div>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</nav>

resources/views/layouts/admin/sidebar.blade.php
<nav id="sidebar" class="active">
    <div class="p-4">
        <h1>
            <a href="{{ route('admin.home') }}" class="logo d-inline-block text-center">
                {{ $app_name }} <small class="text-xs d-block text-white-50">Admin</small>
            </a>
        </h1>
        <ul class="list-unstyled components mb-5">
            <li class="{{ request()->url() == route('admin.home') ? 'active' : '' }}">
                <a href="{{ route('admin.home') }}">
                    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none"
                        stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                        class="feather feather-home">
                        <path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path>
                        <polyline points="9 22 9 12 15 12 15 22"></polyline>
                    </svg>
                    <span>{{ __("Tableau de bord") }}</span>
                </a>
            </li>
            <li class="{{ Str::contains(request()->url(), route('admin.users')) ? 'active' : '' }}">
                <a href="{{ route('admin.users') }}">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none"
                        stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                        class="feather feather-users">
                        <path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"></path>
                        <circle cx="9" cy="7" r="4"></circle>
                        <path d="M23 21v-2a4 4 0 0 0-3-3.87"></path>
                        <path d="M16 3.13a4 4 0 0 1 0 7.75"></path>
                    </svg>
                    <span>{{ __("Utilisateurs") }}</span>
                </a>
            </li>
            <li class="{{ Str::contains(request()->url(), route('admin.payments')) ? 'active' : '' }}">
                <a href="{{ route('admin.payments') }}">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none"
                        stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                        class="feather feather-dollar-sign">
                        <line x1="12" y1="1" x2="12" y2="23"></line>
                        <path d="M17 5H9.5a3.5 3.5 0 0 0 0 7h5a3.5 3.5 0 0 1 0 7H6"></path>
                    </svg>
                    <span>{{ __("Paiements") }}</span>
                </a>
            </li>
            <li class="{{ Str::contains(request()->url(), route('admin.withdrawals')) ? 'active' : '' }}">
                <a href="{{ route('admin.withdrawals') }}">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none"
                        stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                        class="feather feather-credit-card">
                        <rect x="1" y="4" width="22" height="16" rx="2" ry="2"></rect>
                        <line x1="1" y1="10" x2="23" y2="10"></line>
                    </svg>
                    <span>{{ __("Retraits") }}</span>
                </a>
            </li>

            <li class="{{ Str::contains(request()->url(), route('admin.incomes')) ? 'active' : '' }}">
                <a href="{{ route('admin.incomes') }}">

                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none"
                        stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                        class="feather feather-trending-up">
                        <polyline points="23 6 13.5 15.5 8.5 10.5 1 18"></polyline>
                        <polyline points="17 6 23 6 23 12"></polyline>
                    </svg>
                    <span>{{ __("Revenus") }}</span>
                </a>
            </li>

            <li class="{{ Str::contains(request()->url(), route('admin.primes')) ? 'active' : '' }}">
                <a href="{{ route('admin.primes') }}">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none"
                        stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                        class="feather feather-gift">
                        <polyline points="20 12 20 22 4 22 4 12"></polyline>
                        <rect x="2" y="7" width="20" height="5"></rect>
                        <line x1="12" y1="22" x2="12" y2="7"></line>
                        <path d="M12 7H7.5a2.5 2.5 0 0 1 0-5C11 2 12 7 12 7z"></path>
                        <path d="M12 7h4.5a2.5 2.5 0 0 0 0-5C13 2 12 7 12 7z"></path>
                    </svg>
                    <span>{{ __("Primes") }}</span>
                </a>
            </li>
        </ul>
    </div>
</nav>